apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-echo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: websocket-echo-app
  template:
    metadata:
      labels:
        app: websocket-echo-app
    spec:
      containers:
        - name: websocket-echo-app
          image: adityachoubey2512/websocket-echo-app
          ports:
            - containerPort: 8080